
# This is a basic workflow to help you get started with Actions

name: Workflow1

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: 
      workflow2_name:
        description: 'Workflow2 Name for Triggering'
        required: true
        default: 'Workflow2'
      
      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: 'maxxam123'
      
      workflow2_repo_github:
        description: 'GitHub Repository Name'
        required: true
        default: 'k8s_charls'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: test
        run: |
          mkdir folder
          cd folder
          mkdir folder2
          cd folder2
          git clone https://github.com/maxxam123/k8s_charls
          ls -la
          mv k8s_charls/folder2/neues1 neues1
          echo ${{github.run_number}} > neues
          sed -i '19d' neues1
          var=${{ github.run_number }}
          awk -i inplace 'NR==19{print "        image: nginx:v"}1' neues1
          sed -i 19"s/$/$var &/" neues1
          cd ../..
          
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_REPO }}
        with:
          source-directory: 'folder'
          destination-github-username: 'maxxam123'
          destination-repository-name: 'k8s_charls'
          user-email: hennighausenmax@gmail.com
          target-branch: main

