name: py

on:
  push:
   branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker login -u "hennighausen" -p ""
        docker image build -t hennighausen/charls:v1 .
        docker push hennighausen/charls:v1
